# Generated by Django 3.2.6 on 2022-01-27 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsentReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='eg Sick', max_length=50, verbose_name='absent reason')),
            ],
        ),
        migrations.CreateModel(
            name='AddTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=50, verbose_name='Training Name')),
                ('facilitaor_name', models.CharField(max_length=50, verbose_name='Facilitator Name')),
                ('organization', models.CharField(max_length=50, verbose_name='Organization')),
                ('days', models.IntegerField(verbose_name='No of Days')),
                ('starting_date', models.DateField(verbose_name='Starting Date:')),
                ('ending_date', models.DateField(verbose_name='Ending Date:')),
            ],
            options={
                'ordering': ['training_name'],
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryGroupName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200, verbose_name='Group Name')),
                ('lga', models.CharField(choices=[('fufore', 'Fufore'), ('girei', 'Girei'), ('yola', 'Yola South'), ('jimeta', 'Yola North')], default='Girei', max_length=50, verbose_name='L.G.A')),
                ('community', models.CharField(max_length=200, verbose_name='Community')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('group_leader', models.CharField(max_length=50, verbose_name='Group Leader')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Phone Number')),
            ],
            options={
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, verbose_name='Full Name:')),
                ('community', models.CharField(max_length=200, verbose_name='Community:')),
                ('subject', models.CharField(max_length=30, verbose_name='Subject:')),
                ('complaints', models.TextField(verbose_name='Complaint:')),
                ('complaint_date', models.DateField(auto_now_add=True, verbose_name='Complaint Date:')),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pare_app.beneficiarygroupname')),
            ],
            options={
                'ordering': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('status', models.BooleanField(default=False, verbose_name='Present / Absent')),
                ('late', models.BooleanField(default=False, verbose_name='Late')),
                ('absent_reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pare_app.absentreason')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='staff')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Full Name')),
                ('reply', models.TextField(verbose_name='Reply')),
                ('reply_date', models.DateField(auto_now_add=True, verbose_name='Reply Date:')),
                ('comment', models.BooleanField(default=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pare_app.complaint')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['reply'],
            },
        ),
    ]
